//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace voetbalcrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerPosition
    {
        public string PlayerName { get; set; }
        public int AmountKeep { get; set; }
        public int AmountMidfield { get; set; }
        public int AmountAttack { get; set; }
        public int AmountDefend { get; set; }
        public int PlayerPositionID { get; set; }
        public int PlayerID { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
    }
}
