//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace voetbalcrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
<<<<<<< HEAD
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.TeamPlayer = new HashSet<TeamPlayer>();
        }
    
        public int ID { get; set; }
        public string PlayerName { get; set; }
=======
        public int ID { get; set; }
>>>>>>> otherbranch
        public int Keep { get; set; }
        public int Defend { get; set; }
<<<<<<< HEAD

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamPlayer> TeamPlayer { get; set; }
=======
        public int Attack { get; set; }
        public int Midfield { get; set; }
        public string PlayerName { get; set; }
>>>>>>> otherbranch
    }
}
