//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace voetbalcrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
<<<<<<< HEAD
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.TeamPlayer = new HashSet<TeamPlayer>();
        }
    
        public int ID { get; set; }
        public int SetupID { get; set; }
        public string TeamName { get; set; }
    
        public virtual Setup Setup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamPlayer> TeamPlayer { get; set; }
=======
        public int ID { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> Attack { get; set; }
        public Nullable<int> Defend { get; set; }
        public Nullable<int> Keep { get; set; }
        public Nullable<int> Midfield { get; set; }
>>>>>>> otherbranch
    }
}
