//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace voetbalcrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int PlayerPositionID { get; set; }
        public int PlayerID { get; set; }
        public string TeamName { get; set; }
        public int TeamID { get; set; }
    
        public virtual PlayerPosition PlayerPosition { get; set; }
    }
}
